anchors:
  - &latest-xcode "11.7.0"
  - &latest-ios   "13.7"
  - &min-ios      "12.2"
  - &beta-xcode   "12.0.0"
  - &beta-ios     "14.0"

executors:
  mac:
    working_directory: ~/SalesforceMobileSDK-iOS-Hybrid
    macos:
      xcode: *latest-xcode
    shell: /bin/bash --login -eo pipefail
    environment:
      BASH_ENV: ~/.bashrc
      FASTLANE_SKIP_UPDATE_CHECK: "true"
      CHRUBY_VER: 2.7.1
  mac-beta:
    working_directory: ~/SalesforceMobileSDK-iOS-Hybrid
    macos:
      xcode: *beta-xcode
    shell: /bin/bash --login -eo pipefail
    environment:
      BASH_ENV: ~/.bashrc
      FASTLANE_SKIP_UPDATE_CHECK: "true"
      CHRUBY_VER: 2.7.1

version: 2.1
jobs:
  run-tests:
    parameters:
      lib:
        type: string
        default: "SalesforceHybridSDK"
      device:
        type: string
        default: "iPhone 11"
      ios:
        type: string
        default: *latest-ios
      lane:
        type: string
        default: "test"
      env: 
        type: executor
        default: "mac"
    executor: << parameters.env >> 
    environment:
      LIB: << parameters.lib >> 
      DEVICE: << parameters.device >>
      IOS_VERSION: << parameters.ios >>
    parallelism: 5
    steps:
      - checkout
      - restore_cache: 
          key: v6-gems-{{ checksum ".circleci/Gemfile.lock" }}
      - run: 
          name: Installing gem dependencies
          command:  |
            npm install shelljs@0.8.3
            ./install.sh
            ./build/pre-build
            cd .circleci
            chruby ${CHRUBY_VER}
            sudo bundle update --bundler
            bundle check || sudo bundle install
            sudo bundle update
      - save_cache: 
          key: v6-gems-{{ checksum ".circleci/Gemfile.lock" }}
          paths:
            - /Users/distiller/.gem/ruby/${CHRUBY_VER}
      - run: 
          name: Compile
          command:  |
            chruby ${CHRUBY_VER}
            cd .circleci
            bundle exec fastlane build lib:<< parameters.lib >> 
      - run: 
            name: Run Tests
            command:  |
              chruby ${CHRUBY_VER}
              cd .circleci
              fastlane << parameters.lane >> lib:<< parameters.lib >>
      - run: 
          name: Danger Lib
          command:  |
            chruby ${CHRUBY_VER}
            DANGER_GITHUB_API_TOKEN="279a29d75427e4178cef""b7b5b2d7646c540f025a" danger --dangerfile=.circleci/Dangerfile-Lib.rb --danger_id="${LIB}" --verbose
          background: true
          when: always
      - run: 
          name: Upload code coverage
          command: bash <(curl -s https://codecov.io/bash) -X gcov -X xcode
          background: true
          when: always
      - store_test_results:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/test_output
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/test_output
          destination: Test-Results
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS-Hybrid/.circleci/clangReport
          destination: Static-Analysis

workflows:
  version: 2

  pr-test-hybrid:
    jobs:
      - run-tests:
          matrix:
            parameters:
              lib: ["SalesforceHybridSDK", "SalesforceFileLogger"]
              lane: ["PR"]
          filters:
            branches:
              only:
                - /pull.*/

  # Cron are on a timezone 8 hours ahead of PST
  # Build everything at ~10:30pm Sunday/Wednesday Nights
  hybrid-iOS:
    triggers:
      - schedule:
          cron: "30 6 * * 1,4"
          filters:
            branches:
              only:
                - dev
    jobs:
      - run-tests:
          name: test << matrix.lib >> iOS << matrix.ios >>
          matrix:
            parameters:
              lib: ["SalesforceHybridSDK", "SalesforceFileLogger"]
              ios: [*min-ios, *latest-ios]
              device: ["iPhone 8"]
      - run-tests:
          name: test << matrix.lib >> iOS << matrix.ios >> 
          matrix:
            parameters:
              lib: ["SalesforceHybridSDK", "SalesforceFileLogger"]
              ios: [*beta-ios]
              env: [mac-beta]